option(ENABLE_ADDRESS_SANITIZER "Enable Address Sanitizers" OFF)
if (ENABLE_ADDRESS_SANITIZER)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=address -fsanitize-address-use-after-scope")
    add_link_options("-fsanitize=address")
    add_link_options("-fsanitize-address-use-after-scope")
endif ()

option(ENABLE_THREAD_SANITIZER "Enable Thread Sanitizer" OFF)
if (ENABLE_THREAD_SANITIZER)
    add_compile_options("-fsanitize=thread")
    add_link_options("-fsanitize=thread")
endif ()

option(ENABLE_UNDEFINED_BEHAVIOR_SANITIZER "Enable Undefined Behavior Sanitizer" OFF)
if (ENABLE_UNDEFINED_BEHAVIOR_SANITIZER)
    add_compile_options("-fsanitize=undefined")
    add_link_options("-fsanitize=undefined")
endif ()

option(ENABLE_MEMORY_SANITIZER "Enable Memory Sanitizer" OFF)
if (ENABLE_MEMORY_SANITIZER)
    add_compile_options("-fsanitize=memory")
    add_link_options("-fsanitize=memory")
endif ()